version: '2'
services:
  Palmera:
    image: php:73
    working_dir: /app
    ports:
      - 5678:5678
    volumes:
      - ./:/app:delegated
    environment:
        - DB_HOST=127.0.0.1
        - DB_USERNAME=root
        - DB_PASSWORD="1234"
        - DB_DATABASE=palmera
    command: ["php","artisan","serve", "--host", "0.0.0.0", "--port", "5678"]
