version: '2'
services:
  Palmera:
    image: php:73
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - ./:/app:delegated
    command: ["php","artisan","serve", "--host", "0.0.0.0", "--port", "8000"]
